reporter:
  image:
    pullPolicy: Never
    repository: api-reporter-crud
    tag: latest
  logLevel: DEBUG
  logType: pretty
  ports:
    addressPort: 9001
    addressPortAlias: api-reporter
  postgres:
    host: 172.25.143.81
    port: 5432
    name: postgres
    user: nkiver
    pwd: nkiver
    schema: api_report
  restartPolicy: OnFailure

service:
  port: 9001
  type: LoadBalancer

stage: dev
ingressName: 172.25.143.81
ingressPort: 9001
ingressPath: api
apiVersion: v1

trustedAddress: http://frontops-ingress-controller.frontops.svc.k8s.dldevel;http://127.0.0.1:9999

defaults:
  securityContext: {}